apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.backend.POSTGRES_PASSWORD | b64enc | quote }}
  JWT_KEY: {{ .Values.backend.JWT_KEY | b64enc | quote }}

  SECRET_KEY: {{ .Values.frontend.SECRET_KEY | b64enc | quote }}